repos:
  - ambari
  - hdp_utils
  - hdp

repo_properties:
  ambari:
    version: 2.7.1.0
    major_version: 2
    build_number: 169
  hdp_utils:
    version: 1.1.0.22
  hdp:
    version: 3.0.1.0
    major_version: 3
    minor_version: 3.0
    build_number: 187
